apiVersion: tkex.tencent.com/v1alpha1
kind: GameDeployment
metadata:
  name: test-gamedeployment
  namespace: wessonli-test
  labels:
    app: test-gamedeployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: test-gamedeployment
  scaleStrategy:
    podsToDelete:
    - test-gamedeployment-ghrwg
  minReadySeconds: 5
  updateStrategy:
    type: InplaceUpdate
    partition: 0
    maxUnavailable: 1
    maxSurge: 0
    paused: false
    inPlaceUpdateStrategy:
      gracePeriodSeconds: 30
    canary:
      steps:
      - partition: 4
      - pause: {}
      - partition: 2
      - pause: {}
      - hook:
          templateName: test
  preDeleteUpdateStrategy:
    hook:
      templateName: test-inplace
  preInplaceUpdateStrategy:
    hook:
      templateName: test-inplace
  template:
    metadata:
      labels:
        app: test-gamedeployment
    spec:
      containers:
      - name: goserver
        image: mirrors.tencent.com/wessonli-test/goserver:maintainer
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 20m
          limits:
            cpu: 20m
      - name: nginx
        image: nginx
        imagePullPolicy: IfNotPresent
