apiVersion: tkex.tencent.com/v1alpha1
kind: GameStatefulSet
metadata:
  name: test-gamestatefulset
  namespace: wessonli-test
  labels:
    app: test-gamestatefulset
spec:
  serviceName: "test"
  replicas: 5
  selector:
    matchLabels:
      app: test-gamestatefulset
  podManagementPolicy: OrderedReady
  updateStrategy:
    type: InplaceUpdate
    rollingUpdate:
      partition: 0
    paused: false
    inPlaceUpdateStrategy:
      gracePeriodSeconds: 30
    canary:
      steps:
      - hook:
          templateName: test
        partition: 3
        pause: {}
        partition: 2
        pause:
          duration: 60
      - hook:
          templateName: test
        partition: 3
        pause: {}
        partition: 2
        pause:
          duration: 60
  preDeleteUpdateStrategy:
    hook:
      templateName: test
  preInplaceUpdateStrategy:
    hook:
      templateName: test-inplace
  template:
    metadata:
      labels:
        app: test-gamestatefulset
    spec:
      containers:
      - name: goserver
        image: mirrors.tencent.com/wessonli-test/goserver:latest
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 20m
          limits:
            cpu: 20m
      - name: nginx
        image: nginx
        imagePullPolicy: IfNotPresent
