apiVersion: tkex.tencent.com/v1alpha1
kind: HookTemplate
metadata:
  name: test-inplace
  namespace: wessonli-test
spec:
#  args:
#    - name: PodIP
#    - name: PodName
#    - name: PodNamespace
  metrics:
  - name: webtest
    count: 30
    interval: 10s
    failureLimit: 20
    successfulLimit: 5
    failureCondition: "asInt(result) != 1"
    provider:
      web:
        url: http://svc-goserver.wessonli-test:8080/todos/1
        jsonPath: "{$.id}"
  - name: webtest2
    count: 30
    interval: 10s
    failureLimit: 20
    consecutiveSuccessfulLimit: 2
    failureCondition: "asInt(result) != 2"
    provider:
      web:
        url: http://svc-goserver.wessonli-test:8080/todos/2
        jsonPath: "{$.id}"
