apiVersion: tkex.tencent.com/v1alpha1
kind: HookTemplate
metadata:
  name: test
  namespace: wessonli-test
spec:
  # args:
  # - name: PodIP
  # - name: PodName
  # - name: PodNamespace
  # - name: PodContainer[0]
  metrics:
  - name: webtest
    count: 3
    interval: 10s
    failureLimit: 3
    consecutiveSuccessLimit: 3
    successCondition: "asInt(result) < 3"
    provider:
      web:
        url: http://svc-goserver.wessonli-test:8080/todos/1
        jsonPath: "{$.id}"
