apiVersion: apps/v1
kind: Deployment
metadata:
  name: centos7-deployment-31
  namespace: wessonli-test
spec:
  selector:
    matchLabels:
      app: centos7
  revisionHistoryLimit: 3
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  replicas: 1
  template:
    metadata:
      labels:
        app: centos7
    spec:
      containers:
      - name: centos7
        image: nginx
        imagePullPolicy: IfNotPresent
