apiVersion: tkex.tencent.com/v1alpha1
kind: HookTemplate
metadata:
  name: test-inplace
  namespace: wessonli-test
spec:
  args:
    - name: PodIP
    - name: PodName
    - name: PodNamespace
  metrics:
  - name: webtest
    count: 10
    interval: 10s
    failureLimit: 1
    consecutiveSuccessLimit: 2
    FailureCondition: "asInt(result) == 0"
    provider:
      web:
        url: http://svc-goserver.wessonli-test:8080/todos/1
        jsonPath: "{$.id}"
