apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: wessonli-test
spec:
  selector:
    app: centos7
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30007
