apiVersion: types.kubefed.io/v1beta1
kind: FederatedGameDeployment
metadata:
  name: gamedeploy1
  namespace: test-ns
spec:
  template:
    metadata:
      labels:
        app: goserver
        kubefed.io/fed-host: kvm-02
    spec:
      replicas: 6
      selector:
        matchLabels:
          app: goserver
      template:
        metadata:
          labels:
            app: goserver
        spec:
          containers:
          - name: goserver
            image: mirrors.tencent.com/wessonli-test/goserver:latest
            imagePullPolicy: IfNotPresent
            resources:
              limits:
                cpu: 500m
              requests:
                cpu: 200m
            env:
            - name: DEMO
              value: "Hello"
      preDeleteUpdateStrategy:
        hook:
          templateName: test
      preInplaceUpdateStrategy:
        hook:
          templateName: test-inplace
      updateStrategy:
        type: InplaceUpdate
        maxUnavailable: 1
  placement:
    clusters:
    - name: member
    - name: member2
  overrides:
    - clusterName: member
      clusterOverrides:
      - path: "/metadata/labels"
        op: "add"
        value: 
          kubefed.io/fed-member: member
          app: goserver
          kubefed.io/fed-host: kvm-02
    - clusterName: member2
      clusterOverrides:
      - path: "/metadata/labels"
        op: "add"
        value:
          kubefed.io/fed-member: member2
          app: goserver
          kubefed.io/fed-host: kvm-02
#    - clusterName: member
#      clusterOverrides:
#      - path: "/spec/template/metadata/labels"
#        op: "add"
#        value: 
#          kubefed.io/fed-host: kvm-02
#          kubefed.io/fed-member: member
#          app: goserver
#    - clusterName: member2
#      clusterOverrides:
#      - path: "/spec/template/metadata/labels"
#        op: "add"
#        value: 
#          kubefed.io/fed-host: kvm-02
#          kubefed.io/fed-member: member2
#          app: goserver
#    - clusterName: member
#      clusterOverrides:
#      - path: "/spec/selector/matchLabels"
#        op: "add"
#        value: 
#          kubefed.io/fed-host: kvm-02
#          kubefed.io/fed-member: member
#          app: goserver
#    - clusterName: member2
#      clusterOverrides:
#      - path: "/spec/selector/matchLabels"
#        op: "add"
#        value: 
#          kubefed.io/fed-host: kvm-02
#          kubefed.io/fed-member: member2
#          app: goserver
