apiVersion: types.kubefed.io/v1beta1
kind: FederatedDeployment
metadata:
  name: deploy1
  namespace: test-ns
spec:
  template:
    metadata:
      labels:
        app: goserver
        kubefed.io/fed-host: kvm-02
    spec:
      replicas: 2
      selector:
        matchLabels:
          app: goserver
      template:
        metadata:
          labels:
            app: goserver
        spec:
          containers:
          - name: goserver
            image: mirrors.tencent.com/wessonli-test/goserver:latest
            resources:
              limits:
                cpu: 500m
              requests:
                cpu: 200m
  placement:
    clusters:
    - name: member
    - name: member2
  overrides:
    - clusterName: member
      clusterOverrides:
      - path: "/metadata/labels"
        op: "add"
        value: 
          kubefed.io/fed-member: member
          app: goserver
          kubefed.io/fed-host: kvm-02
    - clusterName: member2
      clusterOverrides:
      - path: "/metadata/labels"
        op: "add"
        value:
          kubefed.io/fed-member: member2
          app: goserver
          kubefed.io/fed-host: kvm-02
#    - clusterName: member
#      clusterOverrides:
#      - path: "/spec/template/metadata/labels"
#        op: "add"
#        value: 
#          kubefed.io/fed-host: kvm-02
#          kubefed.io/fed-member: member
#          app: goserver
#    - clusterName: member2
#      clusterOverrides:
#      - path: "/spec/template/metadata/labels"
#        op: "add"
#        value: 
#          kubefed.io/fed-host: kvm-02
#          kubefed.io/fed-member: member2
#          app: goserver
#    - clusterName: member
#      clusterOverrides:
#      - path: "/spec/selector/matchLabels"
#        op: "add"
#        value: 
#          kubefed.io/fed-host: kvm-02
#          kubefed.io/fed-member: member
#          app: goserver
#    - clusterName: member2
#      clusterOverrides:
#      - path: "/spec/selector/matchLabels"
#        op: "add"
#        value: 
#          kubefed.io/fed-host: kvm-02
#          kubefed.io/fed-member: member2
#          app: goserver
