apiVersion: scheduling.kubefed.io/v1alpha1
kind: ReplicaSchedulingPreference
metadata:
  name: goserver-hook
  namespace: test-ns
spec:
  targetKind: FederatedDeployment
  totalReplicas: 6
  clusters:
    member:
      minReplicas: 1
      maxReplicas: 8
      weight: 1
    member2:
      minReplicas: 1
      maxReplicas: 8
      weight: 2
