apiVersion: types.kubefed.io/v1beta1
kind: FederatedDeployment
metadata:
  name: deploy1
  namespace: test-ns
spec:
  template:
    metadata:
      labels:
        app: nginx
        kubefed.io/fed-host: kvm-02
    spec:
      replicas: 2
      selector:
        matchLabels:
          app: nginx
      template:
        metadata:
          labels:
            app: nginx
        spec:
          containers:
          - image: nginx
            name: nginx
            resources:
              limits:
                cpu: 500m
              requests:
                cpu: 200m
  placement:
    clusters:
    - name: member
    - name: member2
  overrides:
    - clusterName: member
      clusterOverrides:
      - path: "/metadata/labels"
        op: "add"
        value: 
          kubefed.io/fed-member: member
          app: nginx
          kubefed.io/fed-host: kvm-02
    - clusterName: member2
      clusterOverrides:
      - path: "/metadata/labels"
        op: "add"
        value:
          kubefed.io/fed-member: member2
          app: nginx
          kubefed.io/fed-host: kvm-02
