apiVersion: types.kubefed.io/v1beta1
kind: FederatedDeployment
metadata:
  name: goserver-hook
  namespace: test-ns
spec:
  template:
    metadata:
      labels:
        app: goserver-hook
        kubefed.io/fed-host: kvm-02
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: goserver-hook
      template:
        metadata:
          labels:
            app: goserver-hook
        spec:
          containers:
          - name: goserver
            image: mirrors.tencent.com/wessonli-test/goserver:latest
            imagePullPolicy: IfNotPresent
  placement:
    clusters:
    - name: member
    - name: member2
  overrides:
    - clusterName: member
      clusterOverrides:
      - path: "/metadata/labels"
        op: "add"
        value: 
          kubefed.io/fed-member: member
          app: goserver-hook
          kubefed.io/fed-host: kvm-02
    - clusterName: member2
      clusterOverrides:
      - path: "/metadata/labels"
        op: "add"
        value:
          kubefed.io/fed-member: member2
          app: goserver-hook
          kubefed.io/fed-host: kvm-02
