apiVersion: types.kubefed.io/v1beta1
kind: FederatedDeployment
metadata:
  name: deploy1
  namespace: test-ns
spec:
  template:
    metadata:
      labels:
        app: nginx
    spec:
      replicas: 2
      selector:
        matchLabels:
          app: nginx
      template:
        metadata:
          labels:
            app: nginx
        spec:
          containers:
          - image: nginx
            name: nginx
            resources:
              limits:
                cpu: 500m
              requests:
                cpu: 200m
  placement:
    clusters:
    - name: member
