apiVersion: apps/v1
kind: Deployment
metadata:
  name: bcs-gamestatefulset-operator
  namespace: bcs-system
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bcs-gamestatefulset-operator
      platform: bk-bcs
  template:
    metadata:
      labels:
        app: bcs-gamestatefulset-operator
        platform: bk-bcs
    spec:
      serviceAccountName: gamestatefulset-operator
      containers:
      - name: bcs-gamestatefulset-operator
        image: bcs-gamestatefulset-operator:latest
        imagePullPolicy: IfNotPresent
        command: ["/data/bcs/bcs-gamestatefulset-operator/container-start.sh"]